### ISSUE TITLE
Builds

### ISSUE THREAD

**Issue by bamhm182** [twosixlabs/macrocoaster#1]
This isn't an issue, but I thought it would be fun to have a place to talk about/show off our builds of this macropad. I picked up the PCB from Shmoocon 24 and liked the idea. I've also been wanting to mess with a bluetooth QMK enabled keypad for a while, so I figured I'd finally get around to trying it out. I bought the required parts for $32.83 on AliExpress and will post back with pictures when I get everything in.

- 11x [Keycaps](https://www.aliexpress.us/item/3256805859712981.html) ($7.60)
- 100x [DO-35 1N4148 Diodes](https://www.aliexpress.us/item/3256805940754058.html) ($1.38)
- 1x [NRF52840 Bluetooth Controller](https://www.aliexpress.us/item/3256806085566324.html) ($9.31)
- 30x [Outemu Brown Switches](https://www.aliexpress.com/item/3256805690299829.html) ($3.72)
- 1x [301230 110mAh battery](https://www.aliexpress.com/item/2251832546143327.html) ($5.48)
- 1x [0.96" OLED SPI/I2C screen](https://www.aliexpress.com/item/3256805849070952.html) ($1.70)
- 5x [EC11 Rotary Encoders & knobs](https://www.aliexpress.com/item/3256805796819763.html) ($3.64)

If you're reading this and have beat me to a build, post your pictures!

**Comment by Engineer-26** [comment]
Thank you so much! It would genuinely make my day to see people build some of these! 

I'll set up a folder for builds so that people can PR their setups and pictures in :)

**Comment by Engineer-26** [comment]
(Closing this so I can track open issues, but please feel free to keep posting here!

**Comment by Engineer-26** [comment]
check out [the builds folder](https://github.com/twosixlabs/macrocoaster/tree/main/builds/) :) We'd love to see yours there!

**Comment by bamhm182** [comment]
Awesome! I'll definitely submit a PR when I get mine done. That's also a good solution!

Side note, can we get the stl for you macrocoaster-coaster? (The frame)

**Comment by Engineer-26** [comment]
absolutely! I posted it [here](https://github.com/twosixlabs/macrocoaster/tree/main/hardware/Cases/), ill add some new/better ones soon too :)

**Comment by bamhm182** [comment]
I started getting my parts in! Still 2 more deliveries, but all of the parts I need to get it working at a base level are in. Going to see if I can find time to get it working before the keycaps and encoders come in. Super excited!

**Comment by Engineer-26** [comment]
looking forward to it as well! 🥳🥳🥳

**Comment by bamhm182** [comment]
Programming and the writeup are going to have to wait until another day, but I finally found time to assemble it!
![Screenshot_20240205-230758](https://github.com/twosixlabs/macrocoaster/assets/920269/f6a2827e-89a3-4a3a-861c-0ffa67c19d91)
